apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: secret-test
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /etc/tkb
      name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: app-credentials
