# Generated by Django 5.2.7 on 2026-05-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('country', models.CharField()),
                ('year_origin', models.IntegerField()),
                ('website_link', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('image', models.ImageField(upload_to='images/')),
                ('imdb', models.CharField()),
                ('year_release', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(choices=[('A', 'Action'), ('c', 'Comedy'), ('D', 'Drama'), ('h', 'Horror'), ('s', 'Sci-fi'), ('d', 'Documentary'), ('a', 'Animation')])),
                ('cost', models.IntegerField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.publisher')),
            ],
        ),
    ]
