# Generated by Django 5.2.7 on 2026-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_publisher_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(),
        ),
    ]
