# Generated by Django 5.2.7 on 2026-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_publisher_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('d', 'Digital'), ('b', 'Blu-ray'), ('D', 'DVD')], default='d'),
        ),
    ]
