# Generated by Django 6.0.4 on 2026-05-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('release_year', models.IntegerField()),
                ('website', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('image', models.ImageField(upload_to='images/')),
                ('isbn', models.CharField()),
                ('release_year', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('book_dimesions', models.CharField()),
                ('cover_type', models.CharField(choices=[('H', 'Hard Cover'), ('P', 'Paperback')])),
                ('category_type', models.CharField(choices=[('R', 'Romance'), ('T', 'Thriller'), ('B', 'Biography'), ('C', 'Classic'), ('D', 'Drama'), ('H', 'History')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.publisher')),
            ],
        ),
    ]
