# Generated by Django 6.0.4 on 2026-05-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_book_price_book_price_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price_new',
            new_name='price',
        ),
    ]
