# Generated by Django 6.0.4 on 2026-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_rename_price_new_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
