# Generated by Django 6.0.3 on 2026-06-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentproperties',
            unique_together=set(),
        ),
    ]
