# Generated by Django 6.0.3 on 2026-06-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agentproperties_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentproperties',
            unique_together={('agent', 'property')},
        ),
    ]
