apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  namespace: shield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-deploy
  template:
    metadata:
      labels:
        app: hello-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
